<?xml version='1.0' encoding='UTF-8'?>
<definitions name="Service" targetNamespace="urn:Service" xmlns:typens="urn:Service" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/">
        
        <message name="LoadSchools"/>
        <message name="LoadSchoolsResponse">
                <part name="LoadSchoolsReturn" type="xsd:string"/>
        </message>
        
        <portType name="GatopolisWSPortType">
                <operation name="LoadSchools">
                        <input message="typens:LoadSchools"/>
                        <output message="typens:LoadSchoolsResponse"/>
                </operation>
        </portType>
        
        <binding name="GatopolisWSBinding" type="typens:GatopolisWSPortType">
                <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
                <operation name="LoadSchools">
                        <soap:operation soapAction="urn:GatopolisWSAction"/>
                        <input>
                                <soap:body namespace="urn:Service" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                        </input>
                        <output>
                                <soap:body namespace="urn:Service" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                        </output>
                </operation>
        </binding>
        
        <service name="ServiceService">
                <port name="GatopolisWSPort" binding="typens:GatopolisWSBinding">
                        <soap:address location="http://gatopolisphp.azurewebsites.net/gatopolis.php"/>
                </port>
        </service>
</definitions>
