<?xml version='1.0' encoding='UTF-8'?>
<definitions name="Service" targetNamespace="urn:Service" xmlns:typens="urn:Service" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/">
        
        <message name="Load"/>
        <message name="LoadResponse">
                <part name="LoadReturn" type="xsd:string"/>
        </message>
        
        <portType name="SchoolWSPortType">
                <operation name="Load">
                        <input message="typens:Load"/>
                        <output message="typens:LoadResponse"/>
                </operation>
        </portType>
        
        <binding name="SchoolWSBinding" type="typens:SchoolWSPortType">
                <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
                <operation name="Load">
                        <soap:operation soapAction="urn:SchoolWSAction"/>
                        <input>
                                <soap:body namespace="urn:Service" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                        </input>
                        <output>
                                <soap:body namespace="urn:Service" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                        </output>
                </operation>
        </binding>
        
        <service name="ServiceService">
                <port name="SchoolWSPort" binding="typens:SchoolWSBinding">
                        <soap:address location="http://gatopolisphp.azurewebsites.net/school_ws.php"/>
                </port>
        </service>
</definitions>
